- name: conditions
  hosts: localhost
  vars_prompt:
  - name: NUMBER
    prompt: enter number
    private: false
  tasks:
  - name: number is lessthan 10
    debug:
      msg: "entered number {{ NUMBER }} is lessthan 10"
    when: NUMBER | int < 10
  - name: number is greaterthan 10
    debug:
      msg: "entered number {{ NUMBER }} is greaterthan or equal to 10"
    when: NUMBER | int >= 10