- name: loops
  hosts: localhost
  tasks:
  - name: print loop
    debug:
      msg: "hello,{{ item }}"
    loop:
    - linux
    - shell
    - ansible 


- name: install packages
  hosts: localhost
  become: yes
  tasks:
  - name: packages installation
    ansible.builtin.dnf:
      name: "{{ item }}"
      state: latest
    loop:
    - postfix
    - nginx
    - mysql 

- name: install packages and uninstall packages
  hosts: localhost
  become: yes
  tasks:
  - name: install and remove package
   dnf:
    name: "{{ item.name }}"
    state: "{{ item.state }}"
  loop:
  - { name: 'mysql', state: 'latest' }
  - { name: 'nginx', state: 'absent' }
  - { name: 'postfix', state: 'absent' }