- name: play1                            #we can write multiple plays in ansible playbook
  hosts: localhost
  tasks:
  - name: play1 from task1
    ansible.builtin.debug:               #debug is same as echo in shellscript to print text
      msg: "hello Iam play1 from task1"
  - name: play1 from task2
    ansible.builtin.debug:               #debug is same as echo in shellscript to print text
      msg: "hello Iam play1 from task2"

- name: play2
  hosts: localhost
  tasks:
  - name: play2 from task1
    ansible.builtin.debug:               
      msg: "hello Iam play2 from task1"
  - name: play1 from task1
    ansible.builtin.debug:               
      msg: "hello Iam play2 from task2"